variables:
    MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
    paths:    
        - .m2/repository/

stages:  
    - build

build: 
    image: maven:3.9.9-amazoncorretto-21 
    stage: build
    script: "mvn clean install"