name: My Simple Pipeline that checks style, builds, tests and packages artifact
on: [push]
jobs:
  Checkstyle-Build-Test-Package:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Setup JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'corretto'
      - name: Package
        run: mvn package
      - name: Upload jar artifact
        uses: actions/upload-artifact@v4
        with:
          path: target/*.jar
